pipeline {
    agent {
        label 'OWN-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        //ansiColor('xterm')
    }
    parameters {
        string(name: 'appVersion', defaultValue: '1.0.0', description: 'What is the application version?')
    }
    environment{
        def appVersion = '' //variable declaration
        nexusUrl = '192.168.56.114:8081/repository/backend'
    }
    stages {
        stage('print the version'){
            steps{
                script{
                    dir('DevOps_Assets/Jenkins/backend-deploy') {
                   
                    //def packageJson = readJSON file: 'package.json'
                    //appVersion = packageJson.version
                    echo "Application version: ${params.appVersion}"
                    }
                    
                }
            }
        }
        /* stage('Init'){
            steps{
                dir('DevOps_Assets/Jenkins/backend-deploy'){
                sh """
                    cd terraform
                    terraform init
                """
                }
                
            }
        }
       stage('Plan'){
            steps{
                dir('DevOps_Assets/Jenkins/backend-deploy'){
                sh """
                    pwd
                    cd terraform
                    terraform plan -var="app_version=${params.appVersion}"
                """
                }
                
            }
        }

        stage('Deploy'){
            steps{
                dir('DevOps_Assets/Jenkins/backend-deploy'){
                sh """
                    cd terraform
                    terraform apply -auto-approve -var="app_version=${params.appVersion}"
                """
                }
                
            }
        } */
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'I will run when pipeline is success'
        }
        failure { 
            echo 'I will run when pipeline is failure'
        }
    }
}
